Added loading animation
devsForFun/devsForFun pull request #37
Opened 2024-11-10 15:08 UTC by Nandan328

2024-11-10 15:20 UTC, CharanMN7 commented
Tasks for the reviewers:
- [ ] Check for responsiveness across different device sizes
- [ ] Double check build local status

2024-11-10 15:22 UTC, CharanMN7 requested changes

2024-11-10 15:22 UTC, CharanMN7 commented on components/ui/loading.tsx
Please change the file name and the component name to a more descriptive name like "LoadingSpinner".

2024-11-10 16:01 UTC, Nandan328 commented on components/ui/loading.tsx
Thanks for pointing that out!
I've changed the files name and component as you suggested.

2024-11-10 19:17 UTC, CharanMN7 commented on components/ui/loading.tsx
Looking good!

2024-11-10 19:17 UTC, CharanMN7 approved these changes

2024-11-13 12:06 UTC, CharanMN7 commented
The loading spiner looks great! Thank you for your contribution @Nandan328 !

2024-11-13 12:06 UTC, merged